[sitespeed_crux]
pattern = ^sitespeed_io\.crux\.
retentions = 60m:40d

[sitespeed_run]
pattern = ^sitespeed_io\.(.*)\.(.*)\.run\.
retentions = 10s:3d

[sitespeed]
pattern = ^sitespeed_io\.
retentions = 10m:40d